version: "3.8"

services:
  fileshare:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./fileshare:/fileshare
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations user &&
             python manage.py makemigrations fileup &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SECRET_KEY=${DSK}
      - DB_HOST=db
      - DB_NAME=fileshare
      - DB_USER=testadmin
      - DB_PASS=${DP}
    depends_on:
      - db

  db:
    container_name: pg_fileshareproject
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=fileshare
      - POSTGRES_USER=testadmin
      - POSTGRES_PASSWORD=${PGP}
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_fileshareproject
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGDP}
    ports:
      - "5050:80"
